env:
  es6: true
  es2020: true
  node: true
extends:
  - airbnb-base
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - import
  - prettier
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '*.config.?s'
  no-console:
    - warn
settings:
  import/resolver:
    node:
